version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/vitejs:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    container_name: backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   # - db
    #   # - redis
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: maindb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   volumes:
  #     - redis-data:/data
  #   ports:
  #     - "6379:6379"

  prisma:
    image: node:20-alpine
    container_name: prisma
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5555:5555"
    command: sh -c "npx prisma studio"
    depends_on:
      - db

volumes:
  postgres-data:
  redis-data:
