CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Drop tables if they exist
DROP TABLE IF EXISTS "push_subscriptions" CASCADE;
DROP TABLE IF EXISTS "connection" CASCADE;
DROP TABLE IF EXISTS "connection_request" CASCADE;
DROP TABLE IF EXISTS "chat" CASCADE;
DROP TABLE IF EXISTS "feed" CASCADE;
DROP TABLE IF EXISTS "user_profile" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

-- Table structure for table "user"
CREATE TABLE "users" (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(255) NOT NULL UNIQUE,
  email varchar(255) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  full_name varchar(255),
  work_history TEXT,
  skills TEXT,
  profile_photo_path varchar(255) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (id)
);

-- Table structure for table "feed"
CREATE TABLE "feed" (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL,
  content text NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT feed_user_id_fk_user_id FOREIGN KEY (user_id) REFERENCES "users" (id) ON DELETE CASCADE
);

-- Table structure for table "chat"
CREATE TABLE "chat" (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  timestamp timestamptz NOT NULL DEFAULT NOW(),
  from_id bigint NOT NULL,
  to_id bigint NOT NULL,
  message text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT chat_from_id_fk_user_id FOREIGN KEY (from_id) REFERENCES "users" (id) ON DELETE CASCADE,
  CONSTRAINT chat_to_id_fk_user_id FOREIGN KEY (to_id) REFERENCES "users" (id) ON DELETE CASCADE
);

-- 
-- Table structure for table connection_request 
--

CREATE TABLE "connection_request" (
    from_id bigint NOT NULL,
    to_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (from_id, to_id),
    CONSTRAINT connection_request_from_id_fk_user_id FOREIGN KEY (from_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT connection_request_to_id_fk_user_id FOREIGN KEY (to_id) REFERENCES users (id) ON DELETE CASCADE
);

-- 
-- Table structure for table connection 
--

CREATE TABLE "connection" (
    from_id bigint NOT NULL,
    to_id bigint NOT NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (from_id, to_id),
    CONSTRAINT connection_from_id_fk_user_id FOREIGN KEY (from_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT connection_to_id_fk_user_id FOREIGN KEY (to_id) REFERENCES users (id) ON DELETE CASCADE
);

--
-- Table structure for table push_subscriptions
--
CREATE TABLE "push_subscriptions" (
  endpoint TEXT NOT NULL PRIMARY KEY,
  user_id bigint NULL,
  keys JSON NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT push_subscriptions_user_id_fk FOREIGN KEY (user_id) 
    REFERENCES users (id) ON DELETE SET NULL
);


--
-- Seeding data
--

INSERT INTO users (username, email, password_hash, full_name, work_history, skills, profile_photo_path, created_at, updated_at) VALUES
  -- ('warrenmichael', 'user1@gmail.com', '$2b$10$HE4TvYyhd9/6H05d/EZjTes8/RoOM6JQ2O4VRp5zmqHxo0cpxid.2', 'warrenmichael', 'Learning mentor, Theatre director, Agricultural engineer', 'become, smile, me', '', NOW(), NOW()),
  -- ('schwartzgregory', 'user2@gmail.com', '$2b$10$5VMglhgW8nft7/FXJEDnGut72fQxoAdbeQ2ZmjkyqJHZnCHAqRpiy', 'schwartzgregory', 'Surveyor  building control, Development worker  international aid, Psychologist  prison and probation services', 'he, place, future', '', NOW(), NOW()),
  -- ('darius73', 'user3@gmail.com', '$2b$10$Ad92QE4ya2KFkCP/rZ0sIOvEOp7z8LREdgswScy1iKqHh5X8/yVXu', 'darius73', 'Legal executive, Theme park manager, Surveyor  mining', 'in, yet, point', '', NOW(), NOW()),
  -- ('crivers', 'user4@gmail.com', '$2b$10$Ap61JWdqZWU/0sEZm0v1BuHhUh2QStRkQ2f5bwWhq59Y0t04rOgmi', 'crivers', 'Clothing/textile technologist, Nurse  adult, Geochemist', 'kid, significant, require', '', NOW(), NOW()),
  -- ('victoriajenkins', 'user5@gmail.com', '$2b$10$g1tbHsr1bKi6c8YiX3TeJ.mr.OUxmawVD3n81hT7BRvlEFGP0MxWK', 'victoriajenkins', 'Journalist  newspaper, Scientist  marine, Tourism officer', 'different, offer, should', '', NOW(), NOW()),
  -- ('martinezerika', 'user6@gmail.com', '$2b$10$ZN9IFuf2K5mkacawDFNWpuZiRzCV9Vnki8dknAMAxCXnPcwgk1HKW', 'martinezerika', 'Financial controller, Data scientist, Civil Service fast streamer', 'morning, kind, hot', '', NOW(), NOW()),
  -- ('cooleymegan', 'user7@gmail.com', '$2b$10$j29lA6BWVyviafCIt38M9.g9JqooPK1MVEpT6nqNd5J36J/fU924K', 'cooleymegan', 'Historic buildings inspector/conservation officer, Planning and development surveyor, Private music teacher', 'now, American, say', '', NOW(), NOW()),
  -- ('ariel12', 'user8@gmail.com', '$2b$10$/NONq23LKSszWyc9Sx42Zuse1X9pSQXVlZhsB7133srgy.XGPspoe', 'ariel12', 'Personnel officer, Surveyor  commercial/residential, Sound technician  broadcasting/film/video', 'step, federal, science', '', NOW(), NOW()),
  -- ('sstewart', 'user9@gmail.com', '$2b$10$iPd7GKUT.uAgE0xyXlHX3uGw3/ayx.yoEZqvlOVWk0X2ryaE1ryYe', 'sstewart', 'Oncologist, Clothing/textile technologist, Research officer  political party', 'of, edge, list', '', NOW(), NOW()),
  -- ('buchananpamela', 'user10@gmail.com', '$2b$10$ZIyL8Sbrey970LaZ7kSMC.gV9jAwgy9qpZiXyWFsEogaX/PXXiP82', 'buchananpamela', 'Software engineer, Commissioning editor, Personal assistant', 'foreign, tonight, long', '', NOW(), NOW());
  ('user1wbd', 'user1wbd@gmail.com', '$2b$10$s.udlwZEYhcpfAhjrwgHcuDiuq.eQbrUbzfUGjDVZAs9wpFpLD1Vu', 'user1wbd', 'Hydrographic surveyor, Metallurgist, Travel agency manager', 'Congress, develop, moment', '', NOW(), NOW()),
  ('user2wbd', 'user2wbd@gmail.com', '$2b$10$.LXKLJ1oHrvkdBq0nPqRPeT2VxvTlUFlwSr3Qy2Knx4vn/fICbcU.', 'user2wbd', 'English as a second language teacher, Forest/woodland manager, Oceanographer', 'affect, difficult, lot', '', NOW(), NOW()),
  ('user3wbd', 'user3wbd@gmail.com', '$2b$10$de17leb5XAhc3NJfl9L0YeADNzHMJG/FDX88B522wvyFmEvlctspO', 'user3wbd', 'Product/process development scientist, Senior tax professional/tax inspector, Health and safety inspector', 'war, offer, kitchen', '', NOW(), NOW()),
  ('user4wbd', 'user4wbd@gmail.com', '$2b$10$801shaKriPJLV9W6Q6HEr.IAFq6yZq.LsX9mEoOSezIyOntkCqOQG', 'user4wbd', 'Ergonomist, Engineer  broadcasting (operations), Journalist  broadcasting', 'statement, former, own', '', NOW(), NOW()),
  ('user5wbd', 'user5wbd@gmail.com', '$2b$10$TgaCNJjHISL1pTofsnAMT.zLFXnBG3.FfycxJsVhv5B/z0jHNqFuG', 'user5wbd', 'Charity officer, Field seismologist, English as a second language teacher', 'station, speech, large', '', NOW(), NOW()),
  ('user6wbd', 'user6wbd@gmail.com', '$2b$10$ax7KJI9jWxfvI69VPpDFTO8/NIVlE4yP2V1IBylQ85l2F6a4FBDv.', 'user6wbd', 'Sport and exercise psychologist, Surveyor  quantity, Programmer  applications', 'believe, reflect, remember', '', NOW(), NOW()),
  ('user7wbd', 'user7wbd@gmail.com', '$2b$10$9O7SOVgQ6ehsVftPbuxbxeEVnTVI5e3HvkQPnisR6QHb.YSaHKnVS', 'user7wbd', 'Industrial/product designer, Acupuncturist, Insurance risk surveyor', 'me, north, line', '', NOW(), NOW()),
  ('user8wbd', 'user8wbd@gmail.com', '$2b$10$Kn68/ZtmJAyXDZTzUHVAguH/bICO6UaQsBEaKjbDJ0cqgE6iAGiaS', 'user8wbd', 'Animator, Engineer  biomedical, Artist', 'if, money, per', '', NOW(), NOW()),
  ('user9wbd', 'user9wbd@gmail.com', '$2b$10$mMWuglrItUTO0R7RixEz3.7vMBstFfXoMzs8CEZnkGwxrWVUeQGda', 'user9wbd', 'Television/film/video producer, Retail buyer, Surveyor  building control', 'religious, represent, involve', '', NOW(), NOW()),
  ('user10wbd', 'user10wbd@gmail.com', '$2b$10$n4kSZC/yDCnoQFS7jzeA2e.DywWvkAjY6vnWSCjOHlFKGHkpLt9P.', 'user10wbd', 'Editor  magazine features, Broadcast journalist, Ceramics designer', 'executive, turn, others', '', NOW(), NOW()),
  ('user11wbd', 'user11wbd@gmail.com', '$2b$10$yDnQRB3DWvg8GnpgDVQn0.sfskC..0GCVHOqG1in/kGI6TjYmmBzi', 'user11wbd', 'Records manager, Runner  broadcasting/film/video, Product designer', 'understand, measure, set', '', NOW(), NOW()),
  ('user12wbd', 'user12wbd@gmail.com', '$2b$10$qpNRJvDdazAnyAPX/iUjSei0H1KaJsiXBXnGC8juSez5Q5A0cRycS', 'user12wbd', 'Armed forces training and education officer, Travel agency manager, Police officer', 'painting, call, bring', '', NOW(), NOW()),
  ('user13wbd', 'user13wbd@gmail.com', '$2b$10$F0BCAAcV2/DcWgvDxibIzOWFn9fBS2evRksYODs6XhzYSraqUhkzq', 'user13wbd', 'Clinical research associate, Primary school teacher, Hydrographic surveyor', 'act, prove, leader', '', NOW(), NOW()),
  ('user14wbd', 'user14wbd@gmail.com', '$2b$10$TaDHT.NrhEbH4PN4EafaO.RU.0dfnV5Ew9qHvYRMGpCZXL5YP0jyS', 'user14wbd', 'TEFL teacher, Museum/gallery curator, Journalist  broadcasting', 'model, daughter, general', '', NOW(), NOW()),
  ('user15wbd', 'user15wbd@gmail.com', '$2b$10$cIca8hESatvYqP9AZqUT8.PaJxiPiBvusnyUoOHBjoJq1MpUUZEm6', 'user15wbd', 'Therapist  art, Dealer, Training and development officer', 'fast, always, husband', '', NOW(), NOW()),
  ('user16wbd', 'user16wbd@gmail.com', '$2b$10$/xGhC.eApIQvRS8Bm5qHYez/0t7cLLYZreGhfamvqMpb.mASTV8oO', 'user16wbd', 'Public house manager, Colour technologist, Public librarian', 'including, eat, glass', '', NOW(), NOW()),
  ('user17wbd', 'user17wbd@gmail.com', '$2b$10$vgi3zVva0A/YxQbp0JmjBORK4VGYVhRTg8Q/OfoHC4h15QQbOm4mC', 'user17wbd', 'Scientist  forensic, Accountant  chartered public finance, Administrator', 'understand, card, challenge', '', NOW(), NOW()),
  ('user18wbd', 'user18wbd@gmail.com', '$2b$10$IKWtg7Os.BvDx2GYYVH.oOp0Jm4JT.OtGJqED41ANQwrL4felTFIS', 'user18wbd', 'Sub, Glass blower/designer, Lecturer  further education', 'at, teach, star', '', NOW(), NOW()),
  ('user19wbd', 'user19wbd@gmail.com', '$2b$10$68JysDACSuYc8Xt0afl4PePxRMOikE3EiSmRyKgGjmgHk0HbVn7ce', 'user19wbd', 'Nature conservation officer, Teacher  special educational needs, Computer games developer', 'may, former, human', '', NOW(), NOW()),
  ('user20wbd', 'user20wbd@gmail.com', '$2b$10$KC/ujjj7JRQ7M7rex5Zpv.Qr3Sv.5qANz1UMTFmA5G6TmW5q.kb.C', 'user20wbd', 'Sports therapist, Human resources officer, Chief Financial Officer', 'cover, writer, rest', '', NOW(), NOW()),
  ('user21wbd', 'user21wbd@gmail.com', '$2b$10$J3knFhOa0sTPR7M23j3UJe.6PVAavwWVkE5PwQ2JzlF2gBUlS/PHW', 'user21wbd', 'Sports administrator, TEFL teacher, Research officer  government', 'throughout, majority, cover', '', NOW(), NOW()),
  ('user22wbd', 'user22wbd@gmail.com', '$2b$10$fddbCVHrgZElJOjWpAdDreo0/C3a87EILqMMAUBayCY0Akfq1ReOC', 'user22wbd', 'Scientist  marine, Retail banker, Investment banker  operational', 'despite, case, teach', '', NOW(), NOW()),
  ('user23wbd', 'user23wbd@gmail.com', '$2b$10$uSmS3UCYd4ZtXI160u04nOQZI3dZy5umDcYjTxy4hVQKUM4Nbqk4e', 'user23wbd', 'Microbiologist, Trade union research officer, Race relations officer', 'station, dinner, trip', '', NOW(), NOW()),
  ('user24wbd', 'user24wbd@gmail.com', '$2b$10$KV0Ip0lIdzXD4r5/h1T8y.MkdvK6kXNeRanXTUqljeDsDAN7kKflG', 'user24wbd', 'Armed forces operational officer, Gaffer, Engineer  structural', 'upon, eight, left', '', NOW(), NOW()),
  ('user25wbd', 'user25wbd@gmail.com', '$2b$10$w/dysweCgtCx.yUeaTUFueMbCzSRuqgPHNZrW.FpibsE/JEFsTcly', 'user25wbd', 'Designer  ceramics/pottery, General practice doctor, Sports coach', 'type, although, sit', '', NOW(), NOW()),
  ('user26wbd', 'user26wbd@gmail.com', '$2b$10$u4pmwqoJd9NjXkSqbq9yue4zoGLzGryvarI3nf/yV.h9BGZ2hFEya', 'user26wbd', 'Best boy, Geophysicist/field seismologist, Accountant  chartered public finance', 'reveal, allow, contain', '', NOW(), NOW()),
  ('user27wbd', 'user27wbd@gmail.com', '$2b$10$7zj3eNzhvFc.W8C5QBtmee1g10VbrFshbEzYbKe5yDgEroIgHa10W', 'user27wbd', 'Engineer  maintenance, Barrister, Therapist  horticultural', 'new, house, wear', '', NOW(), NOW()),
  ('user28wbd', 'user28wbd@gmail.com', '$2b$10$ogU3s.i2PmTai7r8tpJcYu1c2JIKoPz1iNvqM6svlQFwlGX5Oit0C', 'user28wbd', 'Research officer  government, Geophysicist/field seismologist, Sport and exercise psychologist', 'couple, network, court', '', NOW(), NOW()),
  ('user29wbd', 'user29wbd@gmail.com', '$2b$10$tzU6j2cQNcpLV2iYSjnIqul9HtA1nRSEuL7ucpBTaDbz1PB0YiXGS', 'user29wbd', 'Museum education officer, Teacher  primary school, Dispensing optician', 'safe, close, talk', '', NOW(), NOW()),
  ('user30wbd', 'user30wbd@gmail.com', '$2b$10$kbd/55Ohn2Px3T.Lkau7r.cQubLJXGK03JzYcS5lGaNfRRLGm3QDS', 'user30wbd', 'Biochemist  clinical, Facilities manager, Research scientist (life sciences)', 'yeah, activity, control', '', NOW(), NOW()),
  ('user31wbd', 'user31wbd@gmail.com', '$2b$10$jVSsNxOPtT8d3HH0Zdj2zu923VLjE5QawhZr6njoNRS4NSUWKH.hm', 'user31wbd', 'Geographical information systems officer, Leisure centre manager, Investment banker  operational', 'rise, others, west', '', NOW(), NOW()),
  ('user32wbd', 'user32wbd@gmail.com', '$2b$10$6mLp7UfevLvlrOdSw3BpDOIlX2xGvDyZZMzkdKvZG65MsqQq2qt9.', 'user32wbd', 'Health visitor, Sub, Air traffic controller', 'foot, among, consider', '', NOW(), NOW()),
  ('user33wbd', 'user33wbd@gmail.com', '$2b$10$edVD216ug/ifoHqt0HmgFOSvbluqNxWr1AjeNRtGb0Np4BIVtW/py', 'user33wbd', 'Hotel manager, Brewing technologist, Surveyor  quantity', 'put, American, street', '', NOW(), NOW()),
  ('user34wbd', 'user34wbd@gmail.com', '$2b$10$kjYhr3CEf5o2zIZlrw7sJOtQBpM1iijv89egNq6a4MlqVsV.MGUvS', 'user34wbd', 'Investment analyst, Heritage manager, Research officer  trade union', 'international, stand, third', '', NOW(), NOW()),
  ('user35wbd', 'user35wbd@gmail.com', '$2b$10$dSEQIII65CUXzLmZ1H6Gyu/HJXN3phubECWiuiNNotQJUXohEJOvW', 'user35wbd', 'Homeopath, Haematologist, General practice doctor', 'opportunity, rich, man', '', NOW(), NOW()),
  ('user36wbd', 'user36wbd@gmail.com', '$2b$10$HjctjMYMSARpbqgydxwcku47eXMBusH0F3JoPI1oNd8GSTiQE0.1a', 'user36wbd', 'Human resources officer, Metallurgist, Administrator  local government', 'move, something, send', '', NOW(), NOW()),
  ('user37wbd', 'user37wbd@gmail.com', '$2b$10$Snq3J/0kIV8UCmbECzZateoEvbirh3R9Gjx6Dz38AQUNNW6KQ/pOq', 'user37wbd', 'Geologist  engineering, Advertising art director, Media planner', 'our, gun, industry', '', NOW(), NOW()),
  ('user38wbd', 'user38wbd@gmail.com', '$2b$10$pkbKTE8XTfYzMxrmpPTdeOr7Qk7KiudphUrIuRu6mJdnuXczdj6KS', 'user38wbd', 'Designer  exhibition/display, Lighting technician  broadcasting/film/video, Best boy', 'determine, say, alone', '', NOW(), NOW()),
  ('user39wbd', 'user39wbd@gmail.com', '$2b$10$1t6ggz78hCYJrfedkUr6T.ACZ2vOugFm78vrk4qMdPvi3HzA8R3ze', 'user39wbd', 'Higher education careers adviser, Neurosurgeon, Designer  graphic', 'bag, analysis, attention', '', NOW(), NOW()),
  ('user40wbd', 'user40wbd@gmail.com', '$2b$10$9aiqgztX8Ab/9he5la47Ru9wePsvlL3pL5fnA2tKcD1eB2PVYrEeq', 'user40wbd', 'Exercise physiologist, Research scientist (physical sciences), Print production planner', 'paper, eye, site', '', NOW(), NOW()),
  ('user41wbd', 'user41wbd@gmail.com', '$2b$10$tcadf3KyrFVQWgoo6KCQjOWXWyEwtFj7JdLxL6FGq9QRw.jbAwRVG', 'user41wbd', 'Technical author, Teacher  secondary school, Interior and spatial designer', 'century, yeah, authority', '', NOW(), NOW()),
  ('user42wbd', 'user42wbd@gmail.com', '$2b$10$nvP1iIoi4T71nzUe7XrhZu9jjO5ll9BxrJyAb3qSrKWGQHFrZcxaW', 'user42wbd', 'Arts development officer, Dancer, Manufacturing engineer', 'least, try, hand', '', NOW(), NOW()),
  ('user43wbd', 'user43wbd@gmail.com', '$2b$10$95E9WvFxkG5arY4zWs91w.0Ace.4Ix/MVT4ZSpu/./sNXvXBV8yVW', 'user43wbd', 'Corporate investment banker, Higher education lecturer, Scientist  physiological', 'court, husband, effect', '', NOW(), NOW()),
  ('user44wbd', 'user44wbd@gmail.com', '$2b$10$IjmnPV6uukChzRgZs8WW1uo9qMJkUtG6yJwP5WXypPa81iLPEu/xK', 'user44wbd', 'Network engineer, Programme researcher  broadcasting/film/video, Lecturer  further education', 'that, term, about', '', NOW(), NOW()),
  ('user45wbd', 'user45wbd@gmail.com', '$2b$10$oSLfGSdVpZwGn.6/GJlEpef/tcOfiB9v33pZhrC8Ee296qBKfnOSW', 'user45wbd', 'Transport planner, Accommodation manager, Tourism officer', 'person, other, many', '', NOW(), NOW()),
  ('user46wbd', 'user46wbd@gmail.com', '$2b$10$shp07GnkmFgtIOQZy8ookOcAu0RVjVWPTcB7uuciuHSlWp.vFUpjW', 'user46wbd', 'Ophthalmologist, Biomedical engineer, Sports therapist', 'why, late, learn', '', NOW(), NOW()),
  ('user47wbd', 'user47wbd@gmail.com', '$2b$10$nxFgL3Hepj.c78nBwXdipeupvbWMKizIw1cewttHludmM0IR7plza', 'user47wbd', 'Aid worker, Operations geologist, Surveyor  rural practice', 'sort, student, there', '', NOW(), NOW()),
  ('user48wbd', 'user48wbd@gmail.com', '$2b$10$EhoSkIwV6xtvYXGVmiCQEeNnU0I30XyejwQUIe5bHA507TOAFtb/q', 'user48wbd', 'Commercial/residential surveyor, Retail banker, Charity officer', 'quality, others, between', '', NOW(), NOW()),
  ('user49wbd', 'user49wbd@gmail.com', '$2b$10$R1WcQ0oX.8Tc4sW08GVSAu32ZvGs3erK3Q7PUjErP1vPzDoq1y4fS', 'user49wbd', 'Sales executive, Writer, Engineer  petroleum', 'doctor, federal, coach', '', NOW(), NOW()),
  ('user50wbd', 'user50wbd@gmail.com', '$2b$10$nJf2WGws7IlksWZ6rKNj/eZPY4z1pfLtSm2IyjTa4KCs9430HcwRW', 'user50wbd', 'Systems developer, Pathologist, Art gallery manager', 'scientist, decide, here', '', NOW(), NOW()),
  ('user51wbd', 'user51wbd@gmail.com', '$2b$10$o.V7v7QN3kRn00mSJvvc..AyUxyLEDFwhNqEFlV3cDvY2CJ7YcKBW', 'user51wbd', 'Therapist  art, Surveyor  hydrographic, Osteopath', 'section, wife, see', '', NOW(), NOW()),
  ('user52wbd', 'user52wbd@gmail.com', '$2b$10$rYzNIF4T7hI4FqqKX4mGuuf60uer54kacR1VdJ0D0LyxH2oZ6Y0Wu', 'user52wbd', 'Dispensing optician, Production assistant  radio, Psychologist  sport and exercise', 'north, bit, stand', '', NOW(), NOW()),
  ('user53wbd', 'user53wbd@gmail.com', '$2b$10$EvL8HoUGaTUyBrHX7KsJbObGdQ0tqgI4qhQrdFhVgakJ6wdAF6tjS', 'user53wbd', 'Retail merchandiser, Lecturer  higher education, Psychotherapist', 'let, heavy, responsibility', '', NOW(), NOW()),
  ('user54wbd', 'user54wbd@gmail.com', '$2b$10$gH6Aj/OVQr2lgsnnUdzajOcBdHbjcoOPrj5xoG7bWtxuEz4/n2oc.', 'user54wbd', 'Engineer  electrical, Armed forces operational officer, Advice worker', 'child, quickly, happen', '', NOW(), NOW()),
  ('user55wbd', 'user55wbd@gmail.com', '$2b$10$xtXc9cfUofuPW8UaN.8HgOTjPB7MMzPh8HLmMS.DdddNg93dZocIS', 'user55wbd', 'Civil engineer  consulting, Network engineer, Engineer  building services', 'bed, be, project', '', NOW(), NOW()),
  ('user56wbd', 'user56wbd@gmail.com', '$2b$10$VQhW8d9Fc8cpBiWXlCpSOuM20Ciz.T/bIM72/V1m5ALC.cU7aVr1O', 'user56wbd', 'Health and safety adviser, Administrator  local government, Lexicographer', 'manager, no, offer', '', NOW(), NOW()),
  ('user57wbd', 'user57wbd@gmail.com', '$2b$10$0JwQMGBaioFRKKgPmMCm0uDSwJllw0hEOjrCJI5yK8WhBLfV2QVWq', 'user57wbd', 'Tourism officer, Forensic psychologist, Acupuncturist', 'statement, moment, particularly', '', NOW(), NOW()),
  ('user58wbd', 'user58wbd@gmail.com', '$2b$10$PdEo9r73b2IAsXjrdywAMeUzkq1w7uLHmlpxa5LZ4kS3WdXjH1CJ2', 'user58wbd', 'Maintenance engineer, Data scientist, Associate Professor', 'may, allow, free', '', NOW(), NOW()),
  ('user59wbd', 'user59wbd@gmail.com', '$2b$10$M3e/MJLFjG.nNf2EJ9z8XuiFUkaiw/gIPwCty.myzye5YJf0IqAR2', 'user59wbd', 'Scientist  research (medical), Media planner, Arboriculturist', 'method, man, director', '', NOW(), NOW()),
  ('user60wbd', 'user60wbd@gmail.com', '$2b$10$EM9gVmzj0RsABkqz3mU18ORc8RFNDHmhMAYoT.DHwgitNLQ/78Vce', 'user60wbd', 'Electrical engineer, Management consultant, Psychotherapist  dance movement', 'gun, thank, effect', '', NOW(), NOW()),
  ('user61wbd', 'user61wbd@gmail.com', '$2b$10$ykJ1TFQL.S97lKlg.mTlVuLmSljbSObYDell4o3GyDels/DKigADu', 'user61wbd', 'Software engineer, Engineer  civil (consulting), Scientist  research (life sciences)', 'step, some, number', '', NOW(), NOW()),
  ('user62wbd', 'user62wbd@gmail.com', '$2b$10$Stc10I29OqM4Dz2/uaplGuDzqYW6AoG5AqH9VSqCBbUBco.0aHwJ.', 'user62wbd', 'Printmaker, Microbiologist, Race relations officer', 'son, system, them', '', NOW(), NOW()),
  ('user63wbd', 'user63wbd@gmail.com', '$2b$10$qrVPa9Jhh8hV5EzfOzSuaOi97qzYUZCEEqwFCz2SQMl.5LqXDAC.m', 'user63wbd', 'Chartered certified accountant, Chief Strategy Officer, Publishing rights manager', 'watch, field, how', '', NOW(), NOW()),
  ('user64wbd', 'user64wbd@gmail.com', '$2b$10$s0QJF0nGAAt8YbdXHq6EDeBVRDoq7P9XVoaPUF4d8ZB9OBiZTReHe', 'user64wbd', 'Rural practice surveyor, Production manager, Haematologist', 'someone, onto, half', '', NOW(), NOW()),
  ('user65wbd', 'user65wbd@gmail.com', '$2b$10$l.XElfEfXBynnvaF6uF8/OYojcuMAWkLC3gpgBVtfd9GntD261cuS', 'user65wbd', 'Restaurant manager  fast food, Furniture conservator/restorer, Doctor  general practice', 'activity, itself, present', '', NOW(), NOW()),
  ('user66wbd', 'user66wbd@gmail.com', '$2b$10$lUUHNJxTmtkS6KWASLMS9eHo02cOtXTaIkb99yMzARQy/33nPQzpy', 'user66wbd', 'Recruitment consultant, Therapist  horticultural, Haematologist', 'save, social, build', '', NOW(), NOW()),
  ('user67wbd', 'user67wbd@gmail.com', '$2b$10$24gMc/dBqMd7Rv0/BH.mUOHFOEu2yaEDKykePpmlauNZjP8FErzoy', 'user67wbd', 'Aeronautical engineer, Garment/textile technologist, Food technologist', 'inside, military, save', '', NOW(), NOW()),
  ('user68wbd', 'user68wbd@gmail.com', '$2b$10$z7/6cgBuD7kZZrgHOKmOGOPgdo8QVBa.b.csy2Bi0T8n5/5MfDfbW', 'user68wbd', 'Art therapist, Accountant  chartered certified, Dietitian', 'bill, chair, support', '', NOW(), NOW()),
  ('user69wbd', 'user69wbd@gmail.com', '$2b$10$opx5JnHPKwO9jpPzhqE27e4XKD8pG3g5Bhg9fgQLiOls5E24.h/RK', 'user69wbd', 'Environmental manager, Passenger transport manager, Horticultural consultant', 'image, trial, simple', '', NOW(), NOW()),
  ('user70wbd', 'user70wbd@gmail.com', '$2b$10$yfKmidkLhDhrDQBAkPrHGeIo5XMiXOpkeiLA.QZ0vOtiwYcr4gIM6', 'user70wbd', 'Occupational therapist, Engineer  structural, Therapist  horticultural', 'speak, group, above', '', NOW(), NOW()),
  ('user71wbd', 'user71wbd@gmail.com', '$2b$10$K6zU8JSCR0CvIjaDCKcPxuI/VxJ/0zO2cel6Y4/GuOWUkW0RBWJ0m', 'user71wbd', 'Structural engineer, Technical brewer, Arboriculturist', 'article, Congress, always', '', NOW(), NOW()),
  ('user72wbd', 'user72wbd@gmail.com', '$2b$10$MLvDBEY70LQDTGvX1DR7i.XZaRDETqBUSKxgmSywkcIwWFjjP8Qme', 'user72wbd', 'Ambulance person, Teacher  early years/pre, Biomedical engineer', 'better, get, spend', '', NOW(), NOW()),
  ('user73wbd', 'user73wbd@gmail.com', '$2b$10$0t8RS.HlBskx1uvTDBpONOaKl2LMmWwKvJLF5Hw.iNcp1TIvQf0rm', 'user73wbd', 'Accommodation manager, Sports therapist, Analytical chemist', 'that, source, wear', '', NOW(), NOW()),
  ('user74wbd', 'user74wbd@gmail.com', '$2b$10$Sn8kJt5cj7cEAKBNZlzd0.O66FRwWTERoFlC/LrlduWchKPO0TXbO', 'user74wbd', 'Chartered legal executive (England and Wales), International aid/development worker, Careers adviser', 'service, group, fact', '', NOW(), NOW()),
  ('user75wbd', 'user75wbd@gmail.com', '$2b$10$1WVRzb.L29lOTfDV1lbwS..ed1kuiQEi9mwNEU8M6Er/UJDYP5twa', 'user75wbd', 'Air traffic controller, Optician  dispensing, Careers adviser', 'present, series, surface', '', NOW(), NOW()),
  ('user76wbd', 'user76wbd@gmail.com', '$2b$10$c95r40vH9ktVSKV0RsutC.IGLON89C8DdidgnMOibCzpTlNWDLdJy', 'user76wbd', 'Amenity horticulturist, Airline pilot, Visual merchandiser', 'our, dinner, follow', '', NOW(), NOW()),
  ('user77wbd', 'user77wbd@gmail.com', '$2b$10$TpwWB2meo8uNd1I8Z2.diOXlXWTjX.EU2mx7QN3szcMJUiP1UZtLO', 'user77wbd', 'Television production assistant, Acupuncturist, Homeopath', 'their, together, point', '', NOW(), NOW()),
  ('user78wbd', 'user78wbd@gmail.com', '$2b$10$EXjuazkVNRAEsNm8c9Q50O5PdlMb3VEAeGHWu2SK9Fn1VkiJo3n0a', 'user78wbd', 'Sports development officer, Energy manager, Engineer  control and instrumentation', 'road, point, conference', '', NOW(), NOW()),
  ('user79wbd', 'user79wbd@gmail.com', '$2b$10$KTXhfJoatCIp8RybT.4eyu7Zy9uFX.arOdUmIs0vzbz0dhf4omjS.', 'user79wbd', 'Adult nurse, Production assistant  television, Clothing/textile technologist', 'behavior, technology, movement', '', NOW(), NOW()),
  ('user80wbd', 'user80wbd@gmail.com', '$2b$10$2HuAExUfv4kJAqYZe58hb.Oi/V6LkCsH.tu1dEa3QspwKbJFMoYeW', 'user80wbd', 'Retail banker, Dentist, Database administrator', 'traditional, term, tough', '', NOW(), NOW()),
  ('user81wbd', 'user81wbd@gmail.com', '$2b$10$eB1mHgh/oYZdKjibWRwfJ.RbBZodZ3GzTbzvxCb4BkoelFDS47/oW', 'user81wbd', 'Accountant  chartered management, Media planner, Press photographer', 'still, six, report', '', NOW(), NOW()),
  ('user82wbd', 'user82wbd@gmail.com', '$2b$10$OcZf3.oFHQSQRgLPphSqDOqsEZ82wM7d5j1ObvPb9qdBXlrKNBLzK', 'user82wbd', 'Associate Professor, Engineer  land, Librarian  public', 'agree, safe, tell', '', NOW(), NOW()),
  ('user83wbd', 'user83wbd@gmail.com', '$2b$10$pSUO5J8nBD5yeVozZkWSqOdVxj6wc3G53Dqk1mEZ29ebuTkiOYS12', 'user83wbd', 'Scientist  research (physical sciences), Applications developer, Editor  commissioning', 'author, record, deep', '', NOW(), NOW()),
  ('user84wbd', 'user84wbd@gmail.com', '$2b$10$yV.pg5ugKG85du5V0RQ0OOTMbWa85EuTj5DYRciZjEwyRxByJlo1m', 'user84wbd', 'Conference centre manager, Adult nurse, Careers adviser', 'think, language, method', '', NOW(), NOW()),
  ('user85wbd', 'user85wbd@gmail.com', '$2b$10$P5pGdJK1hF76oWKa3VSVlOOXk70Z/hGHCn3Hyd7MP2WqAbDWz6Ufe', 'user85wbd', 'Radio broadcast assistant, Electrical engineer, Environmental health practitioner', 'study, word, bed', '', NOW(), NOW()),
  ('user86wbd', 'user86wbd@gmail.com', '$2b$10$wIHy6uGBv34sCAexlurACOTxqMFko7wRt5r70uPwc3qikceBsfFrS', 'user86wbd', 'Civil Service fast streamer, Freight forwarder, Energy manager', 'light, attack, mouth', '', NOW(), NOW()),
  ('user87wbd', 'user87wbd@gmail.com', '$2b$10$CLJIp0gQ.LuwggysCaNorum/FXYrWIOAq3cFAHNuWMhXHV7V.EBGq', 'user87wbd', 'Teacher  early years/pre, Photographer, Futures trader', 'strong, my, business', '', NOW(), NOW()),
  ('user88wbd', 'user88wbd@gmail.com', '$2b$10$adpFiCHzyNhIhhCJnokQhOdMOLyFUWkxnfxDZQQelueLf3aWY296m', 'user88wbd', 'Energy engineer, Financial adviser, Teacher  adult education', 'stand, treat, real', '', NOW(), NOW()),
  ('user89wbd', 'user89wbd@gmail.com', '$2b$10$wrSDAWY/M49F2e94.HcWIuXiy8YiMtSSfSHh.slzl8Cl98Y2nHXNe', 'user89wbd', 'Training and development officer, Operations geologist, Holiday representative', 'big, particularly, experience', '', NOW(), NOW()),
  ('user90wbd', 'user90wbd@gmail.com', '$2b$10$/szDQuIsrJsLhARRKr0UQODgX7qseKgst7yP4049BuUOnMeU7UONC', 'user90wbd', 'Travel agency manager, Insurance underwriter, Research scientist (physical sciences)', 'course, wonder, investment', '', NOW(), NOW()),
  ('user91wbd', 'user91wbd@gmail.com', '$2b$10$waRSlJK4lFKLbH9pgeV8VOAO2RvrueEKlvyVkNQ6wsVE9cLPPJE1C', 'user91wbd', 'Designer  exhibition/display, Retail merchandiser, Colour technologist', 'high, unit, eight', '', NOW(), NOW()),
  ('user92wbd', 'user92wbd@gmail.com', '$2b$10$0pvWx4JYdYXqNHSyfXHJ3.S5D7z2.jSuy9/rF8FPexgP1b11eOd12', 'user92wbd', 'Quantity surveyor, Geologist  wellsite, Accountant  chartered', 'reflect, current, theory', '', NOW(), NOW()),
  ('user93wbd', 'user93wbd@gmail.com', '$2b$10$SQTMdS6ARVOUJUs3fOfvluj05ra1yOM02vg9HjkdGxhVCzerrtrXe', 'user93wbd', 'Agricultural engineer, Engineer  aeronautical, Scientist  research (life sciences)', 'gas, usually, film', '', NOW(), NOW()),
  ('user94wbd', 'user94wbd@gmail.com', '$2b$10$neg6r2/92zM3X8ymDFXt/.i/1B/JZzw73Y6hRS524.5AOxi8kZtfW', 'user94wbd', 'Meteorologist, Therapist  occupational, Community pharmacist', 'blue, director, condition', '', NOW(), NOW()),
  ('user95wbd', 'user95wbd@gmail.com', '$2b$10$vv4bLRcLDD.x.k4.asSq0uZpJOyK1/PyNRLJSvlChqNKDR5Tc8kmW', 'user95wbd', 'Arts administrator, Physicist  medical, Curator', 'offer, grow, education', '', NOW(), NOW()),
  ('user96wbd', 'user96wbd@gmail.com', '$2b$10$TIzhEijfQJfYwrwrTNs2hO91Wa/hQmPc7/Kl9/7fduH3qMkRDL5oa', 'user96wbd', 'Cabin crew, Therapist  art, Patent examiner', 'detail, option, cut', '', NOW(), NOW()),
  ('user97wbd', 'user97wbd@gmail.com', '$2b$10$NkuCS2pqaZLvN5O/lL/kwO5mtzCzElvpTqhUKQcQMvIZhspdhT9ya', 'user97wbd', 'Horticulturist  commercial, Software engineer, Advertising account executive', 'thing, toward, condition', '', NOW(), NOW()),
  ('user98wbd', 'user98wbd@gmail.com', '$2b$10$iUX97VmvsqoQSBYNIiA/dOnS6a7wuaxCx4mJkdBN.7CtPXryBRUX6', 'user98wbd', 'Volunteer coordinator, Investment banker  corporate, Merchandiser  retail', 'break, cost, family', '', NOW(), NOW()),
  ('user99wbd', 'user99wbd@gmail.com', '$2b$10$QtLwfmHiFQ2S0zlxQ4n4Ru9QIHkudWlETQAitJbidvgLTDnhSX8R2', 'user99wbd', 'Occupational psychologist, Building control surveyor, Psychiatric nurse', 'customer, door, wide', '', NOW(), NOW()),
  ('user100wbd', 'user100wbd@gmail.com', '$2b$10$ZC.jG4fxY8RNt3e32c0/sepaw1X6RQSfXCd1.hMUeX4fLairKaiAe', 'user100wbd', 'Fitness centre manager, Exhibitions officer  museum/gallery, Optometrist', 'note, hotel, school', '', NOW(), NOW());

INSERT INTO feed (content, user_id, created_at, updated_at) VALUES
  ('Kitchen finally senior team join season. Show though soldier plant audience impact. Animal a toward if.', 6, NOW(), NOW()),
  ('By rise treatment first improve Republican. Despite skill interest likely state Democrat huge. Compare eight summer stock baby that production.', 10, NOW(), NOW()),
  ('Between gun trade campaign unit growth table. Suggest quickly require challenge across plant.
Cup inside reach raise record. Describe benefit media meeting letter condition success.', 3, NOW(), NOW()),
  ('Talk husband culture sort. His seek notice college PM room act. Recognize security discussion its city environmental.
Watch daughter east why put kind point. Option small significant bed.', 8, NOW(), NOW()),
  ('She artist citizen security design moment career. Adult too real.
Western possible respond.
Career modern through record I usually point. Personal film mention speak president.', 1, NOW(), NOW()),
  ('Test set economy. Production somebody first couple.
Office attack himself management. Growth arm remain run such. Course difficult oil who.', 3, NOW(), NOW()),
  ('Few research reveal lay opportunity impact. Late large myself simply doctor even yard. Management man fire born over out.', 5, NOW(), NOW()),
  ('Best job miss another. Area family same real claim hot.
Me left reduce work. First still Congress experience. Quite commercial audience. Performance store run newspaper response meet member.', 3, NOW(), NOW()),
  ('Program ten improve child. Similar today before impact. Without wait away around wrong establish.', 1, NOW(), NOW()),
  ('Speech character attack several. Government move old like also billion. Stuff behind big employee defense join.
Real pay return difference herself rest public.', 7, NOW(), NOW()),
  ('According area likely. Stock try them house baby generation nothing when.
Best necessary paper Democrat main. Tough consumer difference matter data offer.', 1, NOW(), NOW()),
  ('Sure describe effect risk son mouth house.
Same kid tree study admit perhaps. Religious natural get tree chance represent pull however.
Than make science. Tax my better century if.', 5, NOW(), NOW()),
  ('Both perform hundred statement carry. Ahead number consider because table. Beat despite deep truth common ask describe.', 9, NOW(), NOW()),
  ('Huge answer see piece someone station. Sometimes almost television blue.
My term car. Deal pattern fight yard.', 4, NOW(), NOW()),
  ('Center expert student together standard. Free respond pretty lead enjoy. Better yourself environmental language case.', 2, NOW(), NOW()),
  ('Page risk simple vote move whose leg beautiful.
Century ground rest economic. Herself long public detail play reality any. Rate almost draw student.', 5, NOW(), NOW()),
  ('Face significant stuff brother level letter window. Agency nation left strong miss better. Training everybody want gun deep.
These reflect evidence lawyer. Science keep yard wonder.', 10, NOW(), NOW()),
  ('Represent instead what help offer school. Form drug card best exactly again event small.
Computer such character wife main. Me yard human cup material. Always stage think.', 7, NOW(), NOW()),
  ('Bag enough such year keep dog if. Actually else themselves challenge letter push continue. Successful station rock attention help.', 7, NOW(), NOW()),
  ('Environmental phone improve recently road. Run exist town half. Skill thought reason light.
Bad thought high. Later human much allow wonder economic serve. Land understand environment fine.', 3, NOW(), NOW());

INSERT INTO chat (from_id, to_id, message, timestamp) VALUES
  (4, 3, 'Message system across rule. Usually watch rich three. Guess he more shake audience.
Red set happy. You help by guy series when we. Although kid also. Executive or oil someone throughout.', NOW()),
  (10, 6, 'Lead feeling list medical choice nice that. Enough goal no simply low movement hard. Must young little world sometimes in body.', NOW()),
  (4, 7, 'And thought available wrong drug.
Produce relate news ok role resource there. Experience half site another high whatever do. Drug teach me service. Long between operation dog plant property onto.', NOW()),
  (8, 9, 'Maybe long nature drug. Avoid character college perform likely tend baby movie.
Price reality contain. West public difference section. Word start firm.', NOW()),
  (8, 1, 'Subject available state know near many discussion. Single image seem read. National pull court before point oil.', NOW()),
  (3, 8, 'Movie dream some. During story yeah agent ever nor interview. Unit former address research attack team.', NOW()),
  (5, 9, 'Cost box result true. Statement ever any. Who sport we that system term much. Public little may test this new fire somebody.
Subject stay hospital Mr assume huge.', NOW()),
  (8, 6, 'Perhaps among help four operation improve. Yeah pick without mission.
Itself religious end somebody. So be almost financial.', NOW()),
  (9, 3, 'Opportunity dinner director produce specific suffer material. Where these process look seven although of.', NOW()),
  (5, 9, 'About recently pull every. Get which together whatever.
Truth bit newspaper occur economy. Reduce phone off sure rest society expert. Store top various debate officer avoid particular accept.', NOW()),
  (2, 5, 'Meeting option face back black read control. Hot serious think thank result.
Quality question cold discover property strong. Building involve consumer cut manage.', NOW()),
  (4, 7, 'Able mean office maintain politics bank quite strategy.
Hospital camera religious low this identify. Two today five manage much send reflect.', NOW()),
  (8, 7, 'Agency raise choose evening test stop star. Remain sound end value manager institution. Past stop institution simple how be.', NOW()),
  (7, 1, 'Democratic wear education hand. Record past professional hard total party. And heavy capital head I up actually.', NOW()),
  (10, 3, 'Generation least among wish create respond.
Customer Republican cup since indeed.', NOW()),
  (1, 10, 'Film mention past raise recent reduce country want. Congress music whom design. Federal however woman.
Story prevent quality almost. Trip arm boy building.', NOW()),
  (9, 10, 'Too little shake music. Free three notice night whose five production. Newspaper return improve season military coach member.
Senior war drive region.', NOW()),
  (2, 1, 'Impact color station deal name direction film.
Red chair particularly Republican participant must. Already common school. Exactly imagine very financial treat fund name.', NOW()),
  (10, 5, 'According subject career can represent score relationship lay. Task smile general occur room rest now into. Develop character total for now forget step social.', NOW()),
  (1, 8, 'Her personal when pick song contain car. Own main rich dinner include reflect available. Occur management religious officer make skill.
With author itself. Form maintain list the myself.', NOW()),
  (2, 6, 'Approach action population. Agreement again evidence. Leader prepare fine age cause. Other protect rate sing eight natural establish half.', NOW()),
  (6, 1, 'Positive anyone large include shake again base box. Town maybe better head well stock yeah realize.
Project use plan. Once friend mention out add. Institution add I who will fight piece.', NOW()),
  (8, 6, 'Cell forget lead. Large your contain enough strong notice. Probably also off section.
Happen including laugh inside stuff. Always believe two business.', NOW()),
  (6, 8, 'Should teach all.
More southern score season final produce. Cell not Mr around.
Interest cold research right north. Husband bring participant order election.', NOW()),
  (1, 9, 'Front inside coach series try. Explain oil career effect power. Summer paper carry fish in.', NOW()),
  (3, 6, 'Still recognize different poor purpose. Executive where avoid several. Decade leader apply project attention.', NOW()),
  (10, 8, 'Successful together chair writer. Know different born president wrong share. Dog another board reflect each trial.', NOW()),
  (10, 6, 'Institution end pick speak author. Political opportunity fly way. Member health billion often ten four.', NOW()),
  (7, 5, 'Be report tough suddenly throw modern its. Represent cold he nice society.
Area tree receive. White significant a be deal fast. She television local.', NOW()),
  (10, 4, 'Political hand performance level one property group. Black community wait administration arm until.', NOW());

INSERT INTO connection (from_id, to_id, created_at) VALUES
  (1, 2, '2024-01-24 18:05:53'),
  (2, 1, '2024-01-24 18:05:53'),
  (10, 8, '2024-03-03 00:56:02'),
  (8, 10, '2024-03-03 00:56:02'),
  (1, 5, '2024-10-13 11:22:33'),
  (5, 1, '2024-10-13 11:22:33'),
  (4, 5, '2024-10-17 19:36:55'),
  (5, 4, '2024-10-17 19:36:55'),
  (1, 7, '2024-02-12 07:40:07'),
  (7, 1, '2024-02-12 07:40:07');

INSERT INTO connection_request (from_id, to_id, created_at) VALUES
  (6, 2, '2024-05-15 23:05:16'),
  (10, 5, '2024-01-28 22:09:27'),
  (8, 7, '2024-01-20 00:04:15'),
  (6, 7, '2024-01-06 03:50:42'),
  (8, 9, '2024-03-27 06:54:20'),
  (6, 10, '2024-05-29 23:03:36'),
  (10, 9, '2024-06-10 11:08:10'),
  (1, 6, '2024-08-06 07:54:19'),
  (1, 9, '2024-03-25 19:17:29'),
  (3, 5, '2024-10-13 06:41:01');

